#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 25 15:15:22 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f0325244ff7e4847b343528a836617e6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot serdiv_wrapper_tb_behav xil_defaultlib.serdiv_wrapper_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto f0325244ff7e4847b343528a836617e6 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot serdiv_wrapper_tb_behav xil_defaultlib.serdiv_wrapper_tb xil_defaultlib.glbl -log elaborate.log

