#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Apr 25 15:15:24 CEST 2025
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim serdiv_wrapper_tb_behav -key {Behavioral:sim_1:Functional:serdiv_wrapper_tb} -tclbatch serdiv_wrapper_tb.tcl -view /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/serdiv_wrapper_tb_behav.wcfg -log simulate.log"
xsim serdiv_wrapper_tb_behav -key {Behavioral:sim_1:Functional:serdiv_wrapper_tb} -tclbatch serdiv_wrapper_tb.tcl -view /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/serdiv_wrapper_tb_behav.wcfg -log simulate.log

