webtalk_init -webtalk_dir /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/Wrapper_MA_single.sim/sim_1/behav/xsim/xsim.dir/serdiv_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 25 15:56:39 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174620556_174620558_210294378_345" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "636c6900-6501-4bf9-92a3-ca0c9863305f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f0325244ff7e4847b343528a836617e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "91" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "830 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2977905889 -regid "174620556_174620558_210294378_345" -xml /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/Wrapper_MA_single.sim/sim_1/behav/xsim/xsim.dir/serdiv_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/Wrapper_MA_single.sim/sim_1/behav/xsim/xsim.dir/serdiv_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /import/lab/users/seckinger/Master-Thesis/masterarbeit/Vivado/Wrapper_MA_single/Wrapper_MA_single.sim/sim_1/behav/xsim/xsim.dir/serdiv_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
